#!/bin/bash

if [ xmonad.hs -nt "$1" ] || [ build -nt "$1" ]; then
    exec stack ghc -- \
        --make xmonad.hs \
        -W \
        -Wall \
        -i \
        -ilib \
        -fforce-recomp \
        -main-is main \
        -O2 \
        -o "$1" \
        2>&1
else
    echo "xmonad.hs unchanged, skipping recompile"
fi
